// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0_3O9gAG2cUM2nI0KZEj52iGcWsCRK9M',
    appId: '1:552215335383:android:7dfe0d330b53416df63b92',
    messagingSenderId: '552215335383',
    projectId: 'chat-flutter-e2fd2',
    storageBucket: 'chat-flutter-e2fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xbCYzhF8mmQVYAL4XXYYhbw_McwKbj0',
    appId: '1:552215335383:ios:e4f9f5c54b3d1353f63b92',
    messagingSenderId: '552215335383',
    projectId: 'chat-flutter-e2fd2',
    storageBucket: 'chat-flutter-e2fd2.appspot.com',
    androidClientId: '552215335383-l6jsgc0e6f2kn4cqgbctmv2oqcepvvh7.apps.googleusercontent.com',
    iosClientId: '552215335383-e30ibf6l5f9sqmjh3l2uaevifiptif75.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
